services:
  - type: web
    name: Aziry-Portfolio
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SMTP_HOST
      - key: SMTP_PORT
      - key: SMTP_SECURE
      - key: SMTP_USER
      - key: SMTP_PASS
      - key: CONTACT_EMAIL
    healthCheckPath: /health
